Perform the todo list app
camilevahviraki/To-do-app-react pull request #2
Opened 2022-05-31 07:51 UTC by camilevahviraki

**In this branch we did the following:**

- Setup the App with react
- Perform the todo list app
- Add linters checkers

2022-05-31 10:01 UTC, SimbaWANGU requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @camilevahviraki 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. ✔️ 
- Gitflow is followed. ✔️ 
- Nice separation of modules and styles.  ✔️ 
- Code works as expected. ✔️
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
- Kindly edit your ReadMe file from the standard React App read me file. This will describe your project fully. You can check the Microverse Template [here](https://github.com/microverseinc/readme-template). In addition, you have two ReadMe files when you only require one. 👍 
![image](https://user-images.githubusercontent.com/57634593/171144398-0ddf375a-d25f-481b-aec7-73bb6b876be5.png)

- Kindly remove the App.js file and its corresponding file. Import the ToDo Container module directly to the Index.js file. This removes the extra step of importing the module which is not necessary. 👍 
![image](https://user-images.githubusercontent.com/57634593/171143978-ca31103c-53bf-4387-b97d-c5e633538f8f.png)
![image](https://user-images.githubusercontent.com/57634593/171144133-b3877bb1-90b1-4288-b2b9-3f2de5dc679f.png)
In this snippets you can see the extra step.

- Please keep in mind that an application should be friendly and usable, therefore try adding the remaining functionalities to the project. 👍 

## Optional suggestions
- For future projects, kindly try to reduce the ignored linter checks. The linters are crucial in allowing for standardization of the codebase. 😸 
- For future projects, kindly increase the number of commit you make. This will allow you to revert a commit with ease in case a bug was introduced while also enhancing the idea of continuous improvement. 😸 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 11:23 UTC, camilevahviraki commented
Hi @SimbaWANGU,
Thank you for your constructive feedback, I gon implement it :100:

2022-06-04 15:59 UTC, SimbaWANGU commented
## STATUS: APPROVED ♻️ 

## Hi @camilevahviraki 👋, 

Good job so far!
There nothing left to say other than it's time to MERGE IT!! 👍 

## To Highlight 🎉
- No linter errors. ✔️ 
- Gitflow is followed. ✔️ 
- Nice separation of modules and styles.  ✔️ 
- Code works as expected. ✔️
- PR has a good title and summary. ✔️

<img src="https://c.tenor.com/65pcDF62so0AAAAC/you-got-it-success.gif"/> 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 15:59 UTC, SimbaWANGU approved these changes

2022-06-05 14:54 UTC, merged